version: '3'
services:
  action-recognition:
    image: action-recognition:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     #please change path, if your directory is different.
     - $HOME/catkin_extras/src/act_recog-docker/act_recog/:/catkin_ws/src/act_recog/
    environment:
      DISPLAY: $DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      ROS_MASTER_URI: $ROS_MASTER_URI
      ROS_IP: $ROS_IP
    working_dir: /catkin_ws
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    #command: nvidia-smi -l 1
    #command: xhost +
    command: rosrun act_recog act_recognition_server.py
